### ISSUE TITLE
500

### ISSUE THREAD

**Issue by AnkushBedadun** [discobeta/ps110#1]
Hey i'm trying to use a simple curl post to get a jwt token but i keep getting "500" back. any idea why?
thanks

**Comment by discobeta** [comment]
Can you provide more details about the error? What does it say in the error log? also, what's your curl command look like.

**Comment by AnkushBedadun** [comment]
"curl -X POST -d "username=admin&password=password123" http://localhost:8000/api-token-auth/ " 
if i do this, I just "500" as a response.
"POST /api-token-auth/ HTTP/1.1" 500 3 < -- i see this on the server terminal

**Comment by discobeta** [comment]
Something probably went wrong with your previous setup and migration steps. Make sure that you run the following commands successfully:

<pre>./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser</pre>

then start the server with debug on:
`DJANGO_DEBUG=True ./manage.py runserver`

and post curl:
<pre>
curl -X POST -d "username=admin&password=password123" http://localhost:8000/api-token-auth/
</pre>

you should see something like this:
<pre>
{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlcl9pZCI6MSwiZW1haWwiOiIiLCJleHAiOjE0OTY0NTQyMjB9.sz5hUlLAq4GLxObikRikPZ0yZYqG1qviLXdYcjt0yoQ"}</pre>
